<script type='text/javascript'>
var str=window.location.href.toString();if(&quot;-1&quot;==str.indexOf(&quot;.com/&quot;)){var str1=str.substring(str.lastIndexOf(&quot;.blogspot.&quot;));if(&quot;-1&quot;==str1.indexOf(&quot;/&quot;))var str2=str1;else var str2=str1.substring(0,str1.indexOf(&quot;/&quot;)+1);window.location.href=window.location.href.toString().replace(str2,&quot;.blogspot.com/ncr/&quot;)}
</script>
<b:if cond='data:blog.pageType == &quot;static_page&quot;'>
<style>
.SideBar,.Intro {display:none;}#main-wrapper{width: 140%; float: none; margin: 0px auto;}
html {overflow-x: hidden;}
.post {width: 120%; margin: 15px auto;} .post h3 a { text-align: center; padding:5px;}
</style>
</b:if>
</head><!--<head><link type='text/css' rel='stylesheet' href='https://www.blogger.com/static/v1/widgets/550702504-css_bundle_v2_rtl.css' />
<link type='text/css' rel='stylesheet' href='https://www.blogger.com/dyn-css/authorization.css?targetBlogID=4174355563980394046&zx=b1a31e63-8f2c-4823-a6e5-ae4c9dda0450' />
<script type="text/javascript">var a="&m=1",d="(^|&)m=",e="?",f="?m=1";function g(){var b=window.location.href,c=b.split(e);switch(c.length){case 1:return b+f;case 2:return 0<=c[1].search(d)?null:b+a;default:return null}}var h=navigator.userAgent;if(-1!=h.indexOf("Mobile")&&-1!=h.indexOf("WebKit")&&-1==h.indexOf("iPad")||-1!=h.indexOf("Opera Mini")||-1!=h.indexOf("IEMobile")){var k=g();k&&window.location.replace(k)};
</script><script type="text/javascript">
if (window.jstiming) window.jstiming.load.tick('headEnd');
</script><script type="text/javascript" src="http://bilokr.googlecode.com/files/jquery.min.js.txt"/><script type='text/javascript'>//<![CDATA[ (function(a) { a.fn.lazyload=function(b){var c={threshold: 0,failurelimit:0,event:"scroll",effect:"show",container:window; }; if(b) { a.extend(c,b); } var d=this;if("scroll"==c.event) { a(c.container).bind("scroll",function(b){var e=0;d.each(function(){if(a.abovethetop(this,c)||a.leftofbegin(this,c)){ } else if(!a.belowthefold(this,c)&&!a.rightoffold(this,c)) { a(this).trigger("appear"); } else { if(e++>c.failurelimit){return false; }}}); var f=a.grep(d,function(a) { return!a.loaded; }); d=a(f); })} this.each(function() { var b=this;if(undefined==a(b).attr("original")){a(b).attr("original",a(b).attr("src")); } if("scroll"!=c.event||undefined==a(b).attr("src")||c.placeholder==a(b).attr("src")||a.abovethetop(b,c)||a.leftofbegin(b,c)||a.belowthefold(b,c)||a.rightoffold(b,c)) { if(c.placeholder){a(b).attr("src",c.placeholder); } else { a(b).removeAttr("src"); } b.loaded=false; } else { b.loaded=true; } a(b).one("appear",function() { if(!this.loaded){a("<img />").bind("load",function(){a(b).hide().attr("src",a(b).attr("original"))[c.effect](c.effectspeed);b.loaded=true; }).attr("src",a(b).attr("original")); }}); if("scroll"!=c.event) { a(b).bind(c.event,function(c){if(!b.loaded){a(b).trigger("appear"); }})}}); a(c.container).trigger(c.event);return this; }; a.belowthefold=function(b,c) { if(c.container===undefined||c.container===window){var d=a(window).height()+a(window).scrollTop(); } else { var d=a(c.container).offset().top+a(c.container).height(); } return d<=a(b).offset().top-c.threshold; }; a.rightoffold=function(b,c) { if(c.container===undefined||c.container===window){var d=a(window).width()+a(window).scrollLeft(); } else { var d=a(c.container).offset().left+a(c.container).width(); } return d<=a(b).offset().left-c.threshold; }; a.abovethetop=function(b,c) { if(c.container===undefined||c.container===window){var d=a(window).scrollTop(); } else { var d=a(c.container).offset().top; } return d>=a(b).offset().top+c.threshold+a(b).height(); }; a.leftofbegin=function(b,c) { if(c.container===undefined||c.container===window){var d=a(window).scrollLeft(); } else { var d=a(c.container).offset().left; } return d>=a(b).offset().left+c.threshold+a(b).width(); }; a.extend(a.expr[":"], { "below-the-fold" :"$.belowthefold(a, {threshold : 0, container: window})","above-the-fold": "!$.belowthefold(a, {threshold : 0, container: window})","right-of-fold":"$.rightoffold(a, {threshold : 0, container: window})","left-of-fold":"!$.rightoffold(a, {threshold : 0, container: window})"; })})(jQuery);$(function() { $("img").lazyload({placeholder: "http://i22.servimg.com/u/f22/15/42/72/40/grey10.gif",effect:"fadeIn",threshold:"-50"; })})//]]></script>
